# Generated by Django 4.0.10 on 2024-01-26 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('dete', models.DateField()),
                ('area', models.CharField(choices=[('GO', 'Golan'), ('GA', 'Galil'), ('NEG', 'Negev'), ('JRU', 'Jerusalem'), ('TA', 'Tel Aviv')], max_length=10)),
                ('price', models.IntegerField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
