# Generated by Django 4.0.10 on 2024-02-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='dete',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='titel',
            new_name='title',
        ),
    ]
