# Generated by Django 4.0.10 on 2024-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_rename_dete_trip_date_rename_titel_trip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
