# Generated by Django 4.0.10 on 2024-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_trip_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='area',
            field=models.CharField(blank=True, choices=[('Golan', 'GO'), ('Galil', 'GA'), ('Negev', 'NEG'), ('Jerusalem', 'JRU'), ('Tel Aviv', 'TA')], max_length=10, null=True),
        ),
    ]
